# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 07 Aug 2014 04:02:08 +0000
*	@ALL	0
*	@user	8
adapp	@user	0
cellular-loc	@user	0
conf-target	@user	0
conf-target	samir	2
cse570	samir	2
cse570	fatima	2
eeg	@user	0
eeg	samir	2
tvws-databases	@user	0
tvws-databases	samir	2
cse570	cse570	1
all-projects	ugupta	1
tvws-databases	ugupta	2
hardware-location	ugupta	2
people-contact	ugupta	2
