<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: ayonchak
 * Date: Wed, 24 Sep 2014 23:46:21 -0400
 */

$conf['title'] = 'Wireless Networking and Systems Laboratory';
$conf['license'] = 'cc-by-sa';
$conf['recent_days'] = 30;
$conf['breadcrumbs'] = 2;
$conf['showuseras'] = 'username';
$conf['toptoclevel'] = '2';
$conf['tocminheads'] = '1';
$conf['maxtoclevel'] = '4';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'backlink,recent,revisions,register';
$conf['refcheck'] = 0;
$conf['updatecheck'] = 0;
$conf['userewrite'] = '2';
$conf['tpl']['A_Centered_Perspective']['trace'] = '0';
$conf['tpl']['A_Centered_Perspective']['main_sidebar_always'] = '0';

// end auto-generated content
