# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 25 Sep 2014 04:27:38 +0000
*	@ALL	0
*	@ws%5floc	2
all-projects	@user	2
all-publications	@user	2
cse370	samir	2
cse370	cse370	1
cse370	@user	1
cse570	samir	2
cse570	fatima	2
cse570	cse570	1
cse570	@ws%5floc	1
cse570	@user	1
hardware-location	@user	2
misc-issues	@user	2
people-contact	@user	2
sidebar	@user	2
start	@user	2
wiki:pages:hardware-location	@user	2
