<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: ayonchak
 * Date: Sun, 28 Sep 2014 21:03:57 -0400
 */

$conf['title'] = 'WINGS Lab';
$conf['license'] = 'cc-by-sa';
$conf['showuseras'] = 'username';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'backlink,recent,revisions,register';
$conf['updatecheck'] = 0;
$conf['useslash'] = 1;
$conf['canonical'] = 1;

// end auto-generated content
